#  vznv fzwy rbtt wut
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: 1aabror@gmail.com
    password: pvkkrtunvtloxuvc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  devtools:
    livereload:
      enabled: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SB_AM?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: root
    password:

mybatis:
  type-aliases-package: com.example.demo.vo
  mapper-locations: mapper/**.xml

custom:
  siteName: 2023_07_SB_AM
  siteMainUri: http://localhost:8080
  emailFrom: 1aabror@gmail.com
  emailFromName: 2023_07_SB_AM

file:
  dir: C:/Users/MSI/OneDrive/사진/upload
